version: "3"

services:
  consul-server:
    image: hashicorp/consul:1.17.1
    container_name: consul-server
    restart: always
    volumes:
     - ./docker-config/server.json:/consul/config/server.json
     - ./docker-config/certs/:/consul/config/certs/
     - ./docker-config/server-acl.json:/consul/config/consul-acl.json
     - ./docker-config/kv_dump.json:/consul/dumps/kv_dump.json
    networks:
      - kvnet
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

  etcd-server:
    image: gcr.io/etcd-development/etcd:v3.5.11
    hostname: etcd-server
    container_name: etcd-server
    command:
      - etcd
      - --name=etcd-server
      - --data-dir=data.etcd
      - --advertise-client-urls=http://etcd-server:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-advertise-peer-urls=http://etcd-server:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --initial-cluster=etcd-server=http://etcd-server:2380
      - --initial-cluster-state=new
      - --initial-cluster-token=etcd-cluster
    ports:
      - "2379"
      - "2380"
    networks:
      - kvnet
  # Util container to run commands inside the cluster. Envelops `docker compose exec`
  # and other scripts
  docutil: &docutil
    build:
      dockerfile: Dockerfile-dind
    container_name: docutil
    tty: true
    privileged: true
    volumes:
      - ./:/opt/kivi-rs/
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker:rw
    networks:
      - kvnet

  # Bootstrap consul automatically on UP command
  consulboot:
    <<: *docutil
    container_name: consulboot
    depends_on:
      - consul-server
    command: ["sh", "./exec/consulboot.sh"]

  # Bootstrap etcd automatically on UP command
  etcdboot:
    <<: *docutil
    container_name: etcdboot
    depends_on:
      - etcd-server
    command: ["sh", "./exec/etcdboot.sh"]

networks:
  kvnet:
    driver: bridge
